// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX-gJfleN6zAUmjE1cN41oqfmWYJIdZTI',
    appId: '1:682751660638:web:6640bc538e21022b7f1acf',
    messagingSenderId: '682751660638',
    projectId: 'ikii-iki',
    authDomain: 'ikii-iki.firebaseapp.com',
    storageBucket: 'ikii-iki.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMnxsanNxyc1pTq-fUTsdvMCVoObJRdg4',
    appId: '1:682751660638:android:7deaa4fdbd2fbae67f1acf',
    messagingSenderId: '682751660638',
    projectId: 'ikii-iki',
    storageBucket: 'ikii-iki.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbGCdGG74hOwd5tJhzV24cEwQiOEzQS1o',
    appId: '1:682751660638:ios:237beb43f07204e37f1acf',
    messagingSenderId: '682751660638',
    projectId: 'ikii-iki',
    storageBucket: 'ikii-iki.appspot.com',
    iosClientId: '682751660638-fstbgngufsrus8cpgcu6kedqrrlg4vor.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbGCdGG74hOwd5tJhzV24cEwQiOEzQS1o',
    appId: '1:682751660638:ios:237beb43f07204e37f1acf',
    messagingSenderId: '682751660638',
    projectId: 'ikii-iki',
    storageBucket: 'ikii-iki.appspot.com',
    iosClientId: '682751660638-fstbgngufsrus8cpgcu6kedqrrlg4vor.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication5',
  );
}
